### ISSUE TITLE
 godot 3.22 Parse Error: Mixed tabs and spaces in indentation.

### ISSUE THREAD

**Issue by sericaer** [binogure-studio/chart-gd#2]
godot 3.22 report error. 

 built-in:11 - Parse Error: Mixed tabs and spaces in indentation.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR

Could you fix this issue? thanks a lot !

**Comment by xsellier** [comment]
Looks like it is coming from you bro.

You need to replace all the tabulation by spaces, or all spaces by tabulation.

**Comment by quendera** [comment]
I confirm the bug.
This is actually from your source code and not on the user end.

PS: I appreciate the work put on this project.

**Comment by xsellier** [comment]
Hey,

Source code uses spaces for indentation, not tabs
When you copy/paste the source if the godot editor is set to use tabulation then it might trigger this error.
