### ISSUE TITLE
 Variable "index" already defined in the scope (at line 606).

### ISSUE THREAD

**Issue by starcin** [binogure-studio/chart-gd#4]
Looks like two stacked for loops use the same iterator.
Added a screenshot below:

![resim](https://user-images.githubusercontent.com/62737425/114842823-e4fe3700-9de1-11eb-8f21-885d8026d69e.png)

**Comment by starcin** [comment]
By the way, fixing this and saving the file causes Godot to fill the document with tabs and raise the Mixed tabs and spaces error.
To prevent the tabs/spaces error, I've opened the script.gd in Notepad++ and replaced all double spaces with tabs.

To fix this main issue, I've changed the iterator name in lines 613 and 614.

**Comment by xsellier** [comment]
Thx, fixed by d30c57628e016877e51833c3c77836391f4d0802
