### ISSUE TITLE
"Parser Error: Mixed tabs and spaces in indentation" upon running example scene

### ISSUE THREAD

**Issue by git12121** [binogure-studio/chart-gd#7]
OS: Windows 10
Godot Version: 3.3.2.stable
Plugin Version: 1.0.0 (version that's on the Godot asset library + d30c57628e016877e51833c3c77836391f4d0802)

![image](https://user-images.githubusercontent.com/28541089/128903081-26073c09-8171-40d9-b1ad-ab1edcbe3a1b.png)

**Comment by xsellier** [comment]
Update submitted, closing this issue.
